### ISSUE TITLE
Volume Goes to Max After Song

### ISSUE THREAD

**Issue by Nu2This** [christopher-dG/pmcli#33]
Every time the song changes the volume goes back to max.

**Comment by christopher-dG** [comment]
That's documented in the readme, and will maybe be fixed in the upcoming rewrite. In the meantime, just use your system volume to adjust as is suggested. 

You can also change the default volume in `mpv` settings (I think [this](https://github.com/Argon-/mpv-config/blob/master/mpv.conf#L115) will do it).
